[2025-06-07T16:32:28.724+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.validate_models manual__2025-06-07T16:31:16.959567+00:00 [queued]>
[2025-06-07T16:32:28.731+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.validate_models manual__2025-06-07T16:31:16.959567+00:00 [queued]>
[2025-06-07T16:32:28.732+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-07T16:32:28.742+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_models> on 2025-06-07 16:31:16.959567+00:00
[2025-06-07T16:32:28.749+0000] {standard_task_runner.py:60} INFO - Started process 531 to run task
[2025-06-07T16:32:28.751+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'validate_models', 'manual__2025-06-07T16:31:16.959567+00:00', '--job-id', '2507', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmp97994f5x']
[2025-06-07T16:32:28.752+0000] {standard_task_runner.py:88} INFO - Job 2507: Subtask validate_models
[2025-06-07T16:32:28.789+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.validate_models manual__2025-06-07T16:31:16.959567+00:00 [running]> on host 67c37b4945e3
[2025-06-07T16:32:28.850+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='validate_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T16:31:16.959567+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T16:31:16.959567+00:00'
[2025-06-07T16:32:28.851+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: python /opt/***/src/models/validate_model.py --test_user_count=100
[2025-06-07T16:33:15.533+0000] {train_deep_model_dag.py:20} INFO - üü© [stdout]:
üèÉ View run movie_recommendation_validation_deep_hybrid at: https://dagshub.com/sacer11/MLOps_movie_rec_apr25.mlflow/#/experiments/11/runs/cbfb4a883d04432db691120bf1b90017
üß™ View experiment at: https://dagshub.com/sacer11/MLOps_movie_rec_apr25.mlflow/#/experiments/11

[2025-06-07T16:33:15.534+0000] {train_deep_model_dag.py:22} WARNING - üü® [stderr]:
2025-06-07 16:32:30,657 - INFO - üöÄ Starte Validierung (Deep Hybrid Only)
2025-06-07 16:32:37,194 - INFO - üì• Deep Hybrid Model & Embeddings geladen ‚Äì Beginne Evaluation
2025-06-07 16:33:03,945 - INFO - üìä precision_10_hybrid_deep: 0.31
2025-06-07 16:33:09,195 - INFO - Aktueller Bestwert precision_10: 0.29 (Version: 5)
2025-06-07 16:33:09,195 - INFO - üèÜ Neuer Bestwert! 0.3100 > 0.2900 (Version: 11)
2025-06-07 16:33:11,181 - INFO - Alias 'best_model' wurde auf Version 11 gesetzt!
2025-06-07 16:33:11,191 - ERROR - ‚ùå Fehler beim Kopieren oder DVC push der _best-Embedding-Datei: [Errno 13] Permission denied: '/opt/***/data/processed/hybrid_deep_embedding_best.csv'
2025-06-07 16:33:15,190 - INFO - üéâ Validation abgeschlossen.

[2025-06-07T16:33:15.535+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-07T16:33:15.546+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deep_models_pipeline, task_id=validate_models, execution_date=20250607T163116, start_date=20250607T163228, end_date=20250607T163315
[2025-06-07T16:33:15.585+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-07T16:33:15.604+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
