[2025-06-01T19:37:19.776+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.validate_models manual__2025-06-01T19:33:09.649118+00:00 [queued]>
[2025-06-01T19:37:19.785+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.validate_models manual__2025-06-01T19:33:09.649118+00:00 [queued]>
[2025-06-01T19:37:19.786+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-01T19:37:19.797+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_models> on 2025-06-01 19:33:09.649118+00:00
[2025-06-01T19:37:19.804+0000] {standard_task_runner.py:60} INFO - Started process 618 to run task
[2025-06-01T19:37:19.806+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'movie_recommendation_pipeline', 'validate_models', 'manual__2025-06-01T19:33:09.649118+00:00', '--job-id', '1244', '--raw', '--subdir', 'DAGS_FOLDER/mlops_movie_dag.py', '--cfg-path', '/tmp/tmpfpx36dqj']
[2025-06-01T19:37:19.807+0000] {standard_task_runner.py:88} INFO - Job 1244: Subtask validate_models
[2025-06-01T19:37:19.845+0000] {task_command.py:423} INFO - Running <TaskInstance: movie_recommendation_pipeline.validate_models manual__2025-06-01T19:33:09.649118+00:00 [running]> on host 7b5591149ab9
[2025-06-01T19:37:19.905+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movie_recommendation_pipeline' AIRFLOW_CTX_TASK_ID='validate_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T19:33:09.649118+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-01T19:33:09.649118+00:00'
[2025-06-01T19:37:19.906+0000] {mlops_movie_dag.py:12} INFO - üü¶ Running command: python /opt/***/src/models/validate_model.py
[2025-06-01T19:38:18.684+0000] {mlops_movie_dag.py:18} INFO - üü© [stdout]:
Everything is up to date.
Everything is up to date.
üèÉ View run validate_predictions at: https://dagshub.com/sacer11/MLOps_movie_rec_apr25.mlflow/#/experiments/3/runs/92f79102149a4c0da0df02416d1d7b22
üß™ View experiment at: https://dagshub.com/sacer11/MLOps_movie_rec_apr25.mlflow/#/experiments/3

[2025-06-01T19:38:18.684+0000] {mlops_movie_dag.py:20} WARNING - üü® [stderr]:
2025-06-01 19:37:21,786 - INFO - üöÄ Starte Validierung der Modelle
2025-06-01 19:37:31,227 - INFO - ‚úÖ DVC Pull erfolgreich f√ºr /opt/***/models/hybrid_model.pkl
2025-06-01 19:37:38,707 - INFO - ‚úÖ DVC Pull erfolgreich f√ºr /opt/***/models/user_model.pkl
2025-06-01 19:37:49,691 - INFO - üì• Daten & Modelle geladen ‚Äì Beginne Evaluation
2025-06-01 19:38:15,050 - INFO - üìä precision_10_hybrid: 0.22
2025-06-01 19:38:15,051 - INFO - üìä precision_10_user:   0.05
2025-06-01 19:38:15,051 - INFO - üì° Logging der Metriken in MLflow
2025-06-01 19:38:18,343 - ERROR - ‚ùå Konnte Alias/Tags/Description nicht setzen: bad argument type for built-in operation
2025-06-01 19:38:18,344 - INFO - üéâ Validation & Registry update abgeschlossen.

[2025-06-01T19:38:18.685+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-01T19:38:18.694+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=movie_recommendation_pipeline, task_id=validate_models, execution_date=20250601T193309, start_date=20250601T193719, end_date=20250601T193818
[2025-06-01T19:38:18.712+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-01T19:38:18.729+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
