[2025-05-31T14:46:39.783+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.train_user_model manual__2025-05-31T14:46:08.419468+00:00 [queued]>
[2025-05-31T14:46:39.789+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.train_user_model manual__2025-05-31T14:46:08.419468+00:00 [queued]>
[2025-05-31T14:46:39.790+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-05-31T14:46:39.799+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_user_model> on 2025-05-31 14:46:08.419468+00:00
[2025-05-31T14:46:39.808+0000] {standard_task_runner.py:60} INFO - Started process 505 to run task
[2025-05-31T14:46:39.811+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'movie_recommendation_pipeline', 'train_user_model', 'manual__2025-05-31T14:46:08.419468+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/mlops_movie_dag.py', '--cfg-path', '/tmp/tmp4mg64gtd']
[2025-05-31T14:46:39.812+0000] {standard_task_runner.py:88} INFO - Job 223: Subtask train_user_model
[2025-05-31T14:46:39.849+0000] {task_command.py:423} INFO - Running <TaskInstance: movie_recommendation_pipeline.train_user_model manual__2025-05-31T14:46:08.419468+00:00 [running]> on host 59c692acafaa
[2025-05-31T14:46:40.125+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movie_recommendation_pipeline' AIRFLOW_CTX_TASK_ID='train_user_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T14:46:08.419468+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-31T14:46:08.419468+00:00'
[2025-05-31T14:49:27.893+0000] {logging_mixin.py:188} WARNING - 2025/05/31 14:49:27 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-31T14:49:36.119+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-31T14:49:36.130+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=movie_recommendation_pipeline, task_id=train_user_model, execution_date=20250531T144608, start_date=20250531T144639, end_date=20250531T144936
[2025-05-31T14:49:36.186+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-31T14:49:36.209+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
